[package]
name = "mdp_project"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.43"
grb = { version = "3.0.1", features = ["gurobi12"] }
rand = "0.8"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
